<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
/** @var array $packages */
// This template is require'd inside Plugin::render_import_page(), so every
// variable here is method-local, not global. The prefix sniff can't see that
// when it scans the file in isolation, so silence its false positives file-wide.
// phpcs:disable WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound
?>
<div class="wrap flexasm-wrap">
	<h1><?php esc_html_e( 'Flexa Site Migrator – Import (Staging)', 'flexa-site-migrator' ); ?></h1>

	<div class="notice notice-warning"><p>
		<strong><?php esc_html_e( 'Warning:', 'flexa-site-migrator' ); ?></strong> <?php esc_html_e( 'this operation will', 'flexa-site-migrator' ); ?> <strong><?php esc_html_e( 'overwrite all files + the database', 'flexa-site-migrator' ); ?></strong> <?php esc_html_e( 'of this staging site.', 'flexa-site-migrator' ); ?>
		<?php esc_html_e( "You may be logged out once it's done (because the users table now holds production's data) — log back in using a production account.", 'flexa-site-migrator' ); ?>
	</p></div>

	<?php \Flexa\SiteMigrator\Health::render(); ?>

	<div class="flexasm-card flexasm-pull-card">
		<h2 style="margin-top:0;">⚡ <?php esc_html_e( 'Pull from production via link', 'flexa-site-migrator' ); ?></h2>
		<p class="description"><?php esc_html_e( 'Paste the link generated by the', 'flexa-site-migrator' ); ?> <em>Tools → Flexa Site Migrator</em> <?php esc_html_e( 'page on production. Staging will download the package and migrate automatically — no manual upload needed.', 'flexa-site-migrator' ); ?></p>
		<div class="flexasm-pull-row">
			<input type="text" id="flexasm-pull-input" placeholder="https://production.com/?flexasm_pull=...&key=...">
			<button type="button" id="flexasm-pull-test" class="button" disabled><?php esc_html_e( 'Test connection', 'flexa-site-migrator' ); ?></button>
		</div>
		<div id="flexasm-pull-testresult" class="flexasm-testresult" style="display:none;"></div>
		<div class="flexasm-pull-row" style="margin-top:8px;">
			<input type="password" id="flexasm-pull-password" placeholder="<?php esc_attr_e( 'Password (if the package has one)', 'flexa-site-migrator' ); ?>" autocomplete="off">
		</div>
		<p style="margin-top:10px;">
			<label><input type="checkbox" id="flexasm-pull-insecure"> <?php esc_html_e( 'Skip SSL verification (only for local/self-signed production:', 'flexa-site-migrator' ); ?> <code>.test</code>, <code>.local</code>…)</label>
		</p>
		<p style="margin-top:6px;">
			<label><input type="checkbox" id="flexasm-pull-confirm"> <?php esc_html_e( 'I understand staging will be completely overwritten.', 'flexa-site-migrator' ); ?></label>
		</p>
		<button id="flexasm-pull-start" class="button button-primary button-hero" disabled><?php esc_html_e( 'Pull &amp; Migrate', 'flexa-site-migrator' ); ?></button>
		<span id="flexasm-pull-spin" class="flexasm-spinner" style="display:none;" aria-hidden="true"></span>
	</div>

	<div class="flexasm-card">
		<h2 style="margin-top:0;"><?php esc_html_e( 'Or select a package already on staging', 'flexa-site-migrator' ); ?></h2>
		<p class="description"><?php esc_html_e( 'Copy the package folder into', 'flexa-site-migrator' ); ?> <code>wp-content/uploads/flexasm-packages/</code> <?php esc_html_e( '(via FTP/File Manager), then reload this page.', 'flexa-site-migrator' ); ?></p>
		<?php if ( empty( $packages ) ) : ?>
			<p><?php esc_html_e( 'No packages found in', 'flexa-site-migrator' ); ?> <code>wp-content/uploads/flexasm-packages/</code>.</p>
		<?php else : ?>
			<table class="widefat striped" id="flexasm-pkg-table">
				<thead><tr><th></th><th><?php esc_html_e( 'Package', 'flexa-site-migrator' ); ?></th><th><?php esc_html_e( 'Source site', 'flexa-site-migrator' ); ?></th><th><?php esc_html_e( 'Created', 'flexa-site-migrator' ); ?></th><th><?php esc_html_e( 'Size', 'flexa-site-migrator' ); ?></th></tr></thead>
				<tbody>
				<?php foreach ( $packages as $flexasm_p ) : ?>
					<tr>
						<td><input type="radio" name="flexasm_pkg" value="<?php echo esc_attr( $flexasm_p['id'] ); ?>"></td>
						<td><code><?php echo esc_html( $flexasm_p['id'] ); ?></code></td>
						<td><?php echo esc_html( $flexasm_p['site_url'] ); ?></td>
						<td><?php echo esc_html( $flexasm_p['created'] ); ?></td>
						<td><?php echo esc_html( $flexasm_p['size'] ); ?></td>
					</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
			<p style="margin-top:16px;">
				<label><input type="checkbox" id="flexasm-confirm"> <?php esc_html_e( 'I understand staging will be completely overwritten.', 'flexa-site-migrator' ); ?></label>
			</p>
			<button id="flexasm-run-import" class="button button-primary button-hero" disabled><?php esc_html_e( 'Run Migrate', 'flexa-site-migrator' ); ?></button>
		<?php endif; ?>
	</div>

	<div class="flexasm-card" id="flexasm-imp-panel" style="display:none;">
		<div id="flexasm-imp-progress" class="flexasm-progress">
			<div class="flexasm-step" data-step="download" style="display:none;">
				<span class="flexasm-label"><?php esc_html_e( 'Downloading package from production', 'flexa-site-migrator' ); ?></span>
				<div class="flexasm-bar"><i style="width:0%"></i></div>
			</div>
			<div class="flexasm-step" data-step="extract">
				<span class="flexasm-label"><?php esc_html_e( 'Extracting files', 'flexa-site-migrator' ); ?></span>
				<div class="flexasm-bar"><i style="width:0%"></i></div>
			</div>
			<div class="flexasm-step" data-step="db">
				<span class="flexasm-label"><?php esc_html_e( 'Import database + search-replace', 'flexa-site-migrator' ); ?></span>
				<div class="flexasm-bar"><i style="width:0%"></i></div>
			</div>
			<p class="flexasm-status">…</p>
		</div>

		<div id="flexasm-imp-result" class="flexasm-result" style="display:none;">
			<h2>✅ <?php esc_html_e( 'Migration complete', 'flexa-site-migrator' ); ?></h2>
			<p class="flexasm-imp-log"></p>
			<p><a class="flexasm-imp-login" href="#">→ <?php esc_html_e( 'Open wp-admin (log back in if needed)', 'flexa-site-migrator' ); ?></a></p>
		</div>

		<div id="flexasm-imp-error" class="notice notice-error" style="display:none;"><p></p></div>
	</div>
</div>
